### ISSUE TITLE
sns4q

### ISSUE THREAD

**Issue by MegaByte** [Jolmberg/fn22snesticle#1]
The development page surmises the Super Punch Out filename is derived from "SNES for cube." However, it's actually a reference to the game's product code, which is SNS-4Q. The 0 is the ROM revision, as seen here: https://snescentral.com/pcb.php?id=0680&num=0&side=front 471 is Nintendo's internal version number as confirmed by the gigaleak lot check docs -- which also confirms that this was a ROM from Nintendo's archives.

**Comment by Jolmberg** [comment]
Cool, that does make more sense, I'll update the page, thanks for pointing it out!
