### ISSUE TITLE
Add link to emulator source code to README

### ISSUE THREAD

**Issue by BHSPitMonkey** [Jolmberg/fn22snesticle#2]
Sardu recently uploaded the source code ([iaddis/SNESticle](https://github.com/iaddis/SNESticle)). Maybe it should be mentioned in the README now? 🙂

**Comment by Jolmberg** [comment]
Absolutely! This sure took an interesting turn yesterday. Will update the readme and hopefully the homepage too tonight (or so).

**Comment by Jolmberg** [comment]
I thought I closed this ages ago. Must have closed the browser window instead. Oh well, it's fixed either way.
